### Global settings ###
# This file contains a global list of settings. Generally the only thing you
# need to modify is the license_key.

### Available MLAG group settings ###
# These addresses are use in each MLAG pair. The first switch in a pair will
# grab an available address and fill out the run-file.
MLAG_pairs:
  pair1:
    sysmac: "44:39:39:FF:40:92"
    peerlink_ip: ("169.254.255.1", "169.254.255.2")
  pair2:
    sysmac: "44:39:39:FF:40:93"
    peerlink_ip: ("169.254.255.1", "169.254.255.2")
  pair3:
    sysmac: "44:39:39:FF:40:94"
    peerlink_ip: ("169.254.255.1", "169.254.255.2")
  pair4:
    sysmac: "44:39:39:FF:40:95"
    peerlink_ip: ("169.254.255.1", "169.254.255.2")

### Cumulus Linux License ###
# Fill this in with license string obtained via the license portal or signup email.
# It should be in the form of email@address.tld|Base64LicenseString
license_key: "email@address.tld|Base64LicenseString"

### VLANs ###
# These are the L2 VLAN IDs that will be provisioned initially. Additional
# VLANs can be configured after install, or by modifying this list. All VLANs
# will be
VLANs: "1-100"

### Layer3 interfaces ####
# L3 aka "SVI" interfaces for the VLANs.
# This needs some work. Might be better for this to move elsewhere... 
SVI:
  VLAN10:
    ipv4: "192.168.10.3/24"
    alias: "VM 10 Network"
    vrr_ipv4: "192.168.10.1/24"
    vrr_mac: "44:39:39:FF:00:10"
  VLAN20:
    ipv4: "192.168.20.3/24"
    alias: "VM 20 Network"
    vrr_ipv4: "192.168.20.1/24"
    vrr_mac: "44:39:39:FF:00:20"
